In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
tensor = torch.randn(1, 10)
# 假设我们有一个样本，其类别索引为3（例如，在一个有4个类别的数据集中）
class_index = torch.tensor([3])  # 一个包含类别索引的张量

# 使用F.one_hot生成one-hot张量
y = F.one_hot(class_index, num_classes=5)  # num_classes是类别的总数

In [3]:
class FullyConnectedNet(nn.Module):
    def __init__(self, input_size, output_size=5):
        super(FullyConnectedNet, self).__init__()
        # 定义第一个隐藏层
        self.fc1 = nn.Linear(input_size, 7)
        # 定义第二个隐藏层
        self.fc2 = nn.Linear(7, 7)
        # 定义第三个隐藏层
        self.fc3 = nn.Linear(7, 7)
        # 定义输出层
        self.fc4 = nn.Linear(7, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        # 应用第一个隐藏层并使用ReLU激活函数
        x = F.relu(self.fc1(x))
        # 应用第二个隐藏层并使用ReLU激活函数
        x = F.relu(self.fc2(x))
        # 应用第三个隐藏层并使用ReLU激活函数
        x = F.relu(self.fc3(x))
        # 应用输出层
        x = self.fc4(x)
        return self.softmax(x)

In [4]:
dim1 = tensor.shape[1]

In [5]:
model = FullyConnectedNet(input_size=dim1)

In [6]:
out = model(tensor)
print(out)

tensor([[0.1862, 0.2323, 0.1798, 0.1592, 0.2424]], grad_fn=<SoftmaxBackward0>)


In [7]:
l = (torch.log(out)*y).sum()

In [8]:
l.backward()

In [35]:
params = model.parameters()

# 遍历并打印参数
for param in params:
    print(param.grad)

tensor([[ 0.0264, -0.0044,  0.0231,  0.0182,  0.0011, -0.0176,  0.0062,  0.0026,
          0.0201, -0.0008],
        [-0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,
         -0.0000,  0.0000],
        [-0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,
         -0.0000,  0.0000],
        [-0.0144,  0.0024, -0.0126, -0.0099, -0.0006,  0.0096, -0.0034, -0.0014,
         -0.0109,  0.0004],
        [-0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,
         -0.0000,  0.0000],
        [-0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,
         -0.0000,  0.0000],
        [ 0.0267, -0.0045,  0.0233,  0.0184,  0.0012, -0.0178,  0.0063,  0.0026,
          0.0203, -0.0008]])
tensor([-0.0149,  0.0000,  0.0000,  0.0081,  0.0000,  0.0000, -0.0150])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, 